name: CI

on:
  push:
    branches: [ integration ]
  pull_request:
    branches: [ integration ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 12.x
      uses: actions/setup-node@v4
      with:
        node-version: 12.x
    - name: Initialize mongo
      run: |
        docker exec -i $(docker ps -q -f ancestor=mongo:4.0) mongo --eval "const databaseName = 'enginemaintenancetest'" < ./database/createAndUpdateMongoDB.js
    - name: Install npm packages
      run: npm install
    - name: Build
      run: npm run tsc
    - name: Create the directory where to upload the images to
      run: mkdir tests/uploads 
    - name: Test
      run: npm run test