name: Node.js CI

on:
  push:
    branches: [ integration ]
  pull_request:
    branches: [ integration ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Create mongoDB Docker container for API testing
      uses: DigiPie/mongo-action@v1.0.1
      with:
          image_version: 4.0
    - name: Initialize mongo
      run: "mongo --eval \"const databaseName = 'enginemaintenancetest'\" ./database/createAndUpdateMongoDB.js"
    - name: Install npm packages
      run: npm install
    - name: Build
      run: npm run tsc
    - name: Create the directory where to upload the images to
      run: mkdir tests/uploads 
    - name: Test
      run: npm run test