name: Node.js CI

on:
  push:
    branches: [ integration ]
  pull_request:
    branches: [ integration ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create mongoDB Docker container for API testing
      uses: DigiPie/mongo-action@v1.0.1
    - name: Initialize mongo
      run: "sudo mongo --eval \"const databaseName = 'enginemaintenancetest'\" ./database/createAndUpdateMongoDB.js"
    - name: Install npm packages
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test